---
name: 'install-wolfictl'
description: |
  Install Wolfictl in the path.

runs:
  using: "composite"
  steps:
    - name: "Install wolfictl onto PATH"
      run: |
        # Copy wolfictl out of the wolfictl image and onto PATH
        TMP=$(mktemp -d)
        docker run --rm -i -v $TMP:/out --entrypoint /bin/sh ghcr.io/wolfi-dev/sdk:latest@sha256:ce7537990d75799756318df5c0f43b65540e2bab25686440f19ad127437bd997 -c "cp /usr/bin/wolfictl /out"
        echo "$TMP" >> $GITHUB_PATH
      shell: bash
