---
name: 'install-wolfictl'
description: |
  Install Wolfictl in the path.

runs:
  using: "composite"
  steps:
    - name: "Install wolfictl onto PATH"
      run: |
        # Copy wolfictl out of the wolfictl image and onto PATH
        TMP=$(mktemp -d)
        docker run --rm -i -v $TMP:/out --entrypoint /bin/sh ghcr.io/wolfi-dev/sdk:latest@sha256:ba99c0801b7ac800bd7452a4616ba29f9296bf2cf1036fbaeeec7c9da6f31961 -c "cp /usr/bin/wolfictl /out"
        echo "$TMP" >> $GITHUB_PATH
      shell: bash
