---
name: 'install-wolfictl'
description: |
  Install Wolfictl in the path.

runs:
  using: "composite"
  steps:
    - name: "Install wolfictl onto PATH"
      run: |
        # Copy wolfictl out of the wolfictl image and onto PATH
        TMP=$(mktemp -d)
        docker run --rm -i -v $TMP:/out --entrypoint /bin/sh ghcr.io/wolfi-dev/sdk:latest@sha256:36fb808d7368510f58c590fb5edeba32058e226185374a79b0ad6ba073818f7e -c "cp /usr/bin/wolfictl /out"
        echo "$TMP" >> $GITHUB_PATH
      shell: bash
