---
name: 'wolfictl-update-gh'
description: |
  Wolfictl Update From GitHub.

inputs:
  repository:
    description: |
      GitHub repository to use org/repo.
    required: true
    default: ""
  token:
    description: |
      GitHub Token or OctoSts token.
    required: true
    default: ""
  git_author_name:
    description: |
      Author name to commit.
    required: true
    default: ""
  git_author_email:
    description: |
      Author emails to commit.
    required: true
    default: ""

runs:
  using: 'docker'
  image: docker://ghcr.io/wolfi-dev/sdk:latest@sha256:ef805e1ece664b247ef7546ae386327b04d74c30863cf7f1a6e57b930ecedbe4
  entrypoint: wolfictl
  args:
    - update
    - https://github.com/${{ inputs.repository }}
    - --release-monitoring-query=false
    - --use-gitsign
    - --github-labels=request-version-update
    - --github-labels=automated pr
  env:
    GITHUB_TOKEN: ${{ inputs.token }}
    GIT_AUTHOR_NAME: ${{ inputs.git_author_name }}
    GIT_AUTHOR_EMAIL: ${{ inputs.git_author_email }}
