---
name: 'wolfictl-update-gh'
description: |
  Wolfictl Update From GitHub.

inputs:
  repository:
    description: |
      GitHub repository to use org/repo.
    required: true
    default: ""
  token:
    description: |
      GitHub Token or OctoSts token.
    required: true
    default: ""
  git_author_name:
    description: |
      Author name to commit.
    required: true
    default: ""
  git_author_email:
    description: |
      Author emails to commit.
    required: true
    default: ""

runs:
  using: 'docker'
  image: docker://ghcr.io/wolfi-dev/sdk:latest@sha256:6d49f779092c0bfacb2296654376aac5607dd946a5cd077f06e05e89a2341495
  entrypoint: wolfictl
  args:
    - update
    - https://github.com/${{ inputs.repository }}
    - --release-monitoring-query=false
    - --use-gitsign
    - --github-labels=request-version-update
    - --github-labels=automated pr
  env:
    GITHUB_TOKEN: ${{ inputs.token }}
    GIT_AUTHOR_NAME: ${{ inputs.git_author_name }}
    GIT_AUTHOR_EMAIL: ${{ inputs.git_author_email }}
