---
name: 'wolfictl-check-updates'
description: |
  Wolfictl Check Updates.

inputs:
  token:
    description: |
      GitHub Token or OctoSts token.
    required: false
    default: ""
  changed_files:
    description: |
      List of changed files to check.
    required: true
    default: ""

runs:
  using: "composite"
  steps:
    - name: wolfictl-check-updates
      uses: docker://ghcr.io/wolfi-dev/sdk:latest@sha256:9a4cb7849e9c851bf6c8a8f766b0b9c51db6ff4788d77ace7f99230cdaa7dba7
      with:
        entrypoint: wolfictl
        args: check update ${{ inputs.changed_files }}
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
