---
name: 'wolfictl-check-updates'
description: |
  Wolfictl Check Updates.

inputs:
  token:
    description: |
      GitHub Token or OctoSts token.
    required: false
    default: ""
  changed_files:
    description: |
      List of changed files to check.
    required: true
    default: ""

runs:
  using: "composite"
  steps:
    - name: wolfictl-check-updates
      uses: docker://ghcr.io/wolfi-dev/sdk:latest@sha256:ef805e1ece664b247ef7546ae386327b04d74c30863cf7f1a6e57b930ecedbe4
      with:
        entrypoint: wolfictl
        args: check update ${{ inputs.changed_files }}
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
