---
name: 'wolfictl-check-updates'
description: |
  Wolfictl Check Updates.

inputs:
  token:
    description: |
      GitHub Token or OctoSts token.
    required: false
    default: ""
  changed_files:
    description: |
      List of changed files to check.
    required: true
    default: ""

runs:
  using: "composite"
  steps:
    - name: wolfictl-check-updates
      uses: docker://ghcr.io/wolfi-dev/sdk:latest@sha256:2a2aa0bb3fe671ad36445f77f6d15ea3db56e6f056943b1ba204ddfff5bc051b
      with:
        entrypoint: wolfictl
        args: check update ${{ inputs.changed_files }}
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
